### ISSUE TITLE
update for the latest pocketmine?

### ISSUE THREAD

**Issue by sooluh** [BlockHorizons/DynMapPMMP#10]
I hope and ask for help, this DynMapPMMP can support the latest version of Poketmine at the moment :)

**Comment by Sandertv** [comment]
Sorry, but this plugin was never finished (and never will be, I'm afraid), so updating it will be rather pointless.

**Comment by sooluh** [comment]
why so heavy for you? what are the obstacles? are there any difficulties in certain parts? or indeed this is impossible for pocketmine? if i understand how pocketmine works maybe i can develop it, because in my mind there is only a website and i think this is useful for the makers of the bedrock minecraft server. thank you and I'm sorry I was presumptuous

**Comment by HimbeersaftLP** [comment]
Feel free to fork and update the plugin.

**Comment by sooluh** [comment]
Before I apologize, I want to know what are the obstacles that made you stop continuing this project?
