### ISSUE TITLE
Incorrect statement on the site

### ISSUE THREAD

**Issue by inxomnyaa** [BlockHorizons/DynMapPMMP#7]
https://github.com/BlockHorizons/DynMapPMMP/blob/aa2440e0d4eb0e08b804ea50a4830205ec7eac3a/web/index.html#L40-L41
"Ping"ing you about that, thats not actually true. There are conversion sockets for PE<=>PC map programs based on google maps or similar, and there was DynMapPE, a repo by me which existed ages ago ;)

**Comment by Sandertv** [comment]
Would you please mind stop making these nonsensical issues? There's no point in trying to make a competition out of this, nor am I in the mood for it.

**Comment by HimbeersaftLP** [comment]
@thebigsmileXD "The first of it's kind" doesn't implicitly say what "it's kind" is. Could be the first one from BlockHorizons or the first one for "the new PocketMine"
