### ISSUE TITLE
Hi i want to say something

### ISSUE THREAD

**Issue by inxomnyaa** [BlockHorizons/DynMapPMMP#8]
Hi

**Comment by HimbeersaftLP** [comment]
Hello

**Comment by Sandertv** [comment]
I don't like having to block somebody because of idiocy, but you almost seem to leave me no choice.

**Comment by inxomnyaa** [comment]
> idiocy

;joy: `¯\_(ツ)_/¯ ヽ(^◇^*)/ `
Hey @HimbeersaftLP
